// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyClo9MwyfI5JyyJlO3mBB2lyhogViLom-4',
    appId: '1:396156224056:web:9801e38e8d5afa80bcdccd',
    messagingSenderId: '396156224056',
    projectId: 'rail-sahayak-1a4f3',
    authDomain: 'rail-sahayak-1a4f3.firebaseapp.com',
    storageBucket: 'rail-sahayak-1a4f3.firebasestorage.app',
    measurementId: 'G-81PNL5LD5L',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCowqJrqksCb8WnnaepGeDJiOx96r8bwXQ',
    appId: '1:396156224056:android:1e6d5e7e31bf7ad4bcdccd',
    messagingSenderId: '396156224056',
    projectId: 'rail-sahayak-1a4f3',
    storageBucket: 'rail-sahayak-1a4f3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCxmxy9elGGfSHo7ebrrsJ3AOFvWQVXE00',
    appId: '1:396156224056:ios:0afeb6877ad25aa8bcdccd',
    messagingSenderId: '396156224056',
    projectId: 'rail-sahayak-1a4f3',
    storageBucket: 'rail-sahayak-1a4f3.firebasestorage.app',
    androidClientId: '396156224056-mo9c3erc1btht0utm86bpjekut6h905g.apps.googleusercontent.com',
    iosClientId: '396156224056-1akvcp94kn2e9m7k95rgo66e1mbhugee.apps.googleusercontent.com',
    iosBundleId: 'com.example.railSahayakAdmin',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCxmxy9elGGfSHo7ebrrsJ3AOFvWQVXE00',
    appId: '1:396156224056:ios:0afeb6877ad25aa8bcdccd',
    messagingSenderId: '396156224056',
    projectId: 'rail-sahayak-1a4f3',
    storageBucket: 'rail-sahayak-1a4f3.firebasestorage.app',
    androidClientId: '396156224056-mo9c3erc1btht0utm86bpjekut6h905g.apps.googleusercontent.com',
    iosClientId: '396156224056-1akvcp94kn2e9m7k95rgo66e1mbhugee.apps.googleusercontent.com',
    iosBundleId: 'com.example.railSahayakAdmin',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyClo9MwyfI5JyyJlO3mBB2lyhogViLom-4',
    appId: '1:396156224056:web:8a34e95b5e3a4408bcdccd',
    messagingSenderId: '396156224056',
    projectId: 'rail-sahayak-1a4f3',
    authDomain: 'rail-sahayak-1a4f3.firebaseapp.com',
    storageBucket: 'rail-sahayak-1a4f3.firebasestorage.app',
    measurementId: 'G-TCZHW155S3',
  );
}
